# Using official ubuntu image as a parent image
# This image will be pushed to Docker Hub
FROM ubuntu:latest

# Getting the updates for Ubuntu and installing net tools & python into our environment
RUN apt update && apt install -y net-tools && \
#Installing Python
    apt -y install python3.11 && \
    apt -y install python3-pip && \
    pip install Flask && \
 
#Installing dependancies 
    pip install -r requirements.txt 

#Changing directories to the application
WORKDIR /app

#exposing port for traffic
EXPOSE 8000

#Setting variable
ENV FLASK_APP=application

#run the application from the container
CMD [ "flask", "run", "--host=0.0.0.0" ]

