# Using official ubuntu image as a parent image
FROM ubuntu:latest

# Getting the updates for Ubuntu and installing net tools & python into our environment
RUN apt update && apt install -y net-tools

#Installing git
RUN apt -y install git

#copying app
RUN git clone https://github.com/kura-labs-org/kuralabs_deployment_1.git


#Changing directories to the application
WORKDIR /kuralabs_deployment_1

#Installing Python
RUN apt -y install python3.11
RUN apt -y install python3-pip
RUN pip install Flask

# Installing dependancies 
RUN pip install -r /kuralabs_deployment_1/requirements.txt

#exposing port for traffic
EXPOSE 8000

#Setting variable
ENV FLASK_APP=application

#run the application from the container
#ENTRYPOINT FLASK_APP=application.py flask run --host=0.0.0.0
CMD [ "flask", "run", "--host=0.0.0.0" ]
