# Using official ubuntu image as a parent image
FROM ubuntu:latest

# Getting the updates for Ubuntu and installing net tools & python into our environment
RUN apt update && apt install -y net-tools && \
#Installing Python
    apt -y install python3.11 && \
    apt -y install python3-pip && \
    pip install Flask && \
#Installing Git
    apt -y install git && \
#copying app
    git clone https://github.com/kura-labs-org/kuralabs_deployment_1.git && \
# Installing dependancies 
    pip install -r /kuralabs_deployment_1/requirements.txt && rm /kuralabs_deployment_1/README.md && rm /kuralabs_deployment_1/Deployment-1*.pdf

#Changing directories to the application
WORKDIR /kuralabs_deployment_1

#exposing port for traffic
EXPOSE 8000

#Setting variable
ENV FLASK_APP=application

#run the application from the container
CMD [ "flask", "run", "--host=0.0.0.0" ]
